apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 0
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: srinaths119/django:22
        ports:
        - containerPort: 8000

